# * conmech
branches:
#   only:
#   - .
  except:
    # under development
    - feature/cpp_test

# https://github.com/libigl/libigl/blob/master/.travis.yml
language: cpp
dist: trusty
matrix:
  include:
  - name: Linux with py2.7
    os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env: PYTHON=2.7

  - name: Linux with py3.7
    os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env: PYTHON=2.7

  - name: OSX with py2.7
    os: osx
    compiler: clang
    env: PYTHON=2.7

  - name: OSX with py3.7
    os: osx
    compiler: clang
    env: PYTHON=3.7

before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export CXX=g++-4.8 CC=gcc-4.8;
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export CXX=clang++ CC=clang;
  fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "${PYTHON:0:1}" == "3" ]; then
      brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv;
    python -m virtualenv -p python$PYTHON venv;
    source venv/bin/activate;
    # pip install pytest numpy backports.tempfile
  fi

# install:
# - |
#   if [ -n "$PYTHON" ]; then
#       # python setup.py sdist
#       pip install --no-cache-dir -r requirements-dev.txt
#   fi

script:
  - mkdir build
  - pushd build
  # - cmake ${CMAKE_EXTRA}
  #     -DCMAKE_BUILD_TYPE=$CONFIG
  #     ../
  - cmake ..
  - make -j 2
  - ctest --verbose
  - rm -rf build
  # 
  - pip install --no-cache-dir -r requirements-dev.txt
  - pytest

after_success:
  - coveralls
