# https://www.scivision.dev/travis-ci-osx-python/
language: python
python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    name: pip test
    python: 3.7
    install: pip install -e .
  - os: osx
    language: minimal
    install: pip3 install -e .

install: pip install -e .
