# * conmech
# branches:
#   only:
#   except:

language: python
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # - libc++-dev
    - gcc-7
    - g++-7

matrix:
  include:
  - name: "linux with py2.7 gcc"
    os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env:
    - MATRIX_EVAL="export CONFIG=Release"
    - PYTHON=2.7

  - name: "linux with py3.7 gcc"
    os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env:
    - MATRIX_EVAL="export CONFIG=Release"
    - PYTHON=3.7

  # - os: linux
  #   compiler: gcc-7
  #   env:
  #   - MATRIX_EVAL="export CC=gcc-7 CXX=g++-7 CONFIG=Release"

  - name: "macOS xcode10.2 with py2.7"
    os: osx
    language: shell # 'language: python' is an error on Travis CI macOS
    osx_image: xcode10.2  # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
    - PYTHON=2.7

  - name: "macOS xcode10.2 with py3.7"
    os: osx
    language: shell # 'language: python' is an error on Travis CI macOS
    osx_image: xcode10.2  # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
    - PYTHON=3.7

before_install:
- python --version
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "${PYTHON:0:1}" == "3" ]; then
    brew update; brew install python3;
  fi
  pip install --user --upgrade pip virtualenv;
  python -m virtualenv -p python$PYTHON venv;
  source venv/bin/activate;
- python --version

install:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG #${CMAKE_EXTRA_ARGS}
  - make -j 2
  - ctest
  - popd
  - rm -rf build

script:
  - pip install --no-cache-dir -r requirements-dev.txt
  - pytest
  # try import from a different path
  - popd
  - python -c "from pyconmech import StiffnessChecker"

after_success:
  - coveralls

# pybind11 - cmake can't find the right python version if multiple versions exist
# https://github.com/libigl/libigl/blob/master/.travis.yml
# https://github.com/vgc/vgc/issues/42
# https://github.com/vgc/vgc/blob/master/.travis.yml

# reproduce travis ci failure locally with docker
# https://stackoverflow.com/questions/29753560/how-to-reproduce-a-travis-ci-build-environment-for-debugging
# https://gist.github.com/purp/0df77b579031127f10f31ebd202e8fd4

# TypeError: attrib() got an unexpected keyword argument 'convert'
# https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert
