# * conmech
branches:
#   only:
#   - .
  except:
    # under development
    - feature/cpp_test

language: python
dist: trusty
python:
  - "3.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # - libc++-dev
    - gcc-7
    - g++-7

matrix:
  include:
  - os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env:
    - MATRIX_EVAL="export CONFIG=Release"

  - os: linux
    compiler: gcc-7
    env:
    - MATRIX_EVAL="export CC=gcc-7 CXX=g++-7 CONFIG=Release"

  - name: "Python 3.7.5 on macOS xcode9.4"
    os: osx
    language: shell # 'language: python' is an error on Travis CI macOS
    osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
    before_install:
      - python3 --version
      - pip3 install -U pip
  - name: "Python 3.7.5 on macOS xcode10.2"
    os: osx
    language: shell # 'language: python' is an error on Travis CI macOS
    osx_image: xcode10.2  # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
    before_install:
      - python3 --version
      - pip3 install -U pip

install:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG #${CMAKE_EXTRA_ARGS}
  - make -j 2
  - ctest
  - popd
  - rm -rf build

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pip install --no-cache-dir -r requirements-dev.txt
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip3 install --no-cache-dir -r requirements-dev.txt
    fi
  - pytest

after_success:
  - coveralls

# pybind11 - cmake can't find the right python version if multiple versions exist
# https://github.com/libigl/libigl/blob/master/.travis.yml
# https://github.com/vgc/vgc/issues/42
# https://github.com/vgc/vgc/blob/master/.travis.yml

# reproduce travis ci failure locally with docker
# https://stackoverflow.com/questions/29753560/how-to-reproduce-a-travis-ci-build-environment-for-debugging
# https://gist.github.com/purp/0df77b579031127f10f31ebd202e8fd4

# TypeError: attrib() got an unexpected keyword argument 'convert'
# https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert
