# * conmech
branches:
#   only:
#   - .
  except:
    # under development
    - feature/cpp_test

language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    compiler: gcc # 4.8.4 by default on Trusty
    env:
    - MATRIX_EVAL="export CONFIG=Release PYTHON=3"
  - os: osx
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug PYTHON=3"

install:
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - eval "${MATRIX_EVAL}"
  - pip install --no-cache-dir -r requirements-dev.txt

script:
  # - mkdir build
  # - pushd build
  # - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG #${CMAKE_EXTRA_ARGS}
  # - make -j 2
  # - ctest --verbose
  # - popd
  # - rm -rf build
  # - pip install --no-cache-dir -r requirements-dev.txt
  - pytest

after_success:
  - coveralls

# https://github.com/libigl/libigl/blob/master/.travis.yml
# https://github.com/vgc/vgc/issues/42
# https://github.com/vgc/vgc/blob/master/.travis.yml